name: Container Image CI
on: [push]
jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Build the container image
run: docker build . --file Dockerfile --tag localbuild/testimage1:latest
- uses: anchore/scan-action@v3
with:
image: "localbuild/testimage1:latest"
fail-build: false
- name: Create SBOM
uses: anchore/sbom-action@v0
with:
format: --csv
output-file: "${{ github.event.repository.name }}-.csv"
- name: Scan SBOM
uses: anchore/scan-action@v3
with:
sbom: "${{ github.event.repository.name }}-csvv"
